### ISSUE TITLE
Fix for bug in wait_for_join - makes joining WIFI very flaky

### ISSUE THREAD

**Issue by nickaxgit** [soypat/seqs#34]
Hi Patricio

I was having very unreliable initial connection to WIFI networks

Fairly sure this is the fix:- (last line) - it certainly works a lot better

In wifi.go

func (d *Device) wait_for_join(ssid string) (err error) {
	d.eventmask.Enable(whd.EvSET_SSID)
	d.eventmask.Enable(whd.EvAUTH)

	err = d.setSSID(ssid)
	if err != nil {
		return err
	}
	// Poll for async events.
	deadline := time.Now().Add(20 * time.Second)
	keepGoing := true
	for keepGoing {
		time.Sleep(270 * time.Millisecond) //was 270
		err = d.check_status(d._sendIoctlBuf[:])
		if err != nil {
			return err
		}
		// Keep trying until we get a link up/auth failed/timeout.
		//OLD - keepGoing = d.state == linkStateDown && d.state != linkStateUpWaitForSSID && time.Until(deadline) > 0
		keepGoing = (d.state == linkStateDown || d.state == linkStateUpWaitForSSID) && time.Now().Before(deadline)
	}

**Comment by soypat** [comment]
Nick! Neat find. The condition as is `d.state == linkStateDown && d.state != linkStateUpWaitForSSID` does not make a lot of sense really, if the first condition is true the second is always true as well. Your change makes much more sense since the connection process should wait until the auth is done.

Will make change!

**Comment by soypat** [comment]
Fixed in https://github.com/soypat/cyw43439/commit/a40e87e292b55477e07559fb93ad1ea63a3411a5

**Comment by nickaxgit** [comment]
Thanks

Wish I could contribute more/better but the necessity to earn a living gets
in the way. best of luck with the project I would love to see TinyGo
flourish
